# Generated by Django 2.1.5 on 2019-01-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=20)),
                ('g_name_date', models.DateField()),
                ('g_girl_num', models.IntegerField()),
                ('g_boy_num', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_age', models.IntegerField()),
                ('s_sex', models.BooleanField(default=True)),
                ('s_content', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Grade')),
            ],
        ),
    ]
